apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-sqs-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-sqs-consumer
  template:
    metadata:
      labels:
        app: ml-sqs-consumer
    spec:
      containers:
      - name: consumer
        image: 560852306721.dkr.ecr.us-east-1.amazonaws.com/sqs-consumer:latest
        imagePullPolicy: Always
        env:
        - name: QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/560852306721/MLOps-FinalProject-Spring26"
        - name: BUCKET_NAME
          value: "seis765-finalproject-560852306721-us-east-1-an"
        - name: MODEL_KEY
          value: "models/latest/model.pkl"
        - name: REGION_NAME
          value: "us-east-1"
